apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac-test-binding-cluster
subjects:
- kind: ServiceAccount
  name: foo
  apiGroup: ""
  namespace: rbac-test
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""

